### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by LiubovChernohor** [LiubovChernohor/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Andrey7315** [comment]
https://www.facebook.com/DonaldTrump
https://www.donaldjtrump.com/?fbclid=IwAR36QqT6ioPbMeMBoYMykusZFsofOJbwlpfq2fFyR0l42Zyn3e7CFfoEV1A
https://www.instagram.com/realdonaldtrump/?hl=ru

**Comment by LiubovChernohor** [comment]
Дякую-дякую-дякуююююю!
