### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by LiubovChernohor** [LiubovChernohor/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Andrey7315** [comment]
1968
I graduated from the Wharton School of Finance at the University of Pennsylvania  with a degree in economics.
Started my career at my father's real estate development company.
 1971
I became president of the company and began using The Trump Organization as an umbrella brand
1978
my company renovated the derelict Commodore Hotel, adjacent to Grand Central Terminal in Manhattan
1980
I obtained rights to develop Trump Tower, a mixed-use skyscraper in Midtown Manhattan which became my primary residence until 2019
1983
I purchased the New Jersey Generals, a team in the United States Football League.
1984
I opened Harrah's at Trump Plaza, a hotel and casino in Atlantic City, New Jersey. 
 1989 -1990
lent my name to the Tour de Trump cycling stage race
From 1996 to 2015
I owned all or part of the Miss Universe pageants, including Miss USA and Miss Teen USA. In 2007, I received a star on the Hollywood Walk of Fame for his work as producer of Miss Universe.
2015 
I announced my candidacy for president of the United States on the Republican ticket and became the official Republican candidate for president on July 19, 2016
on November 8, 2016, 
I become the 45th president of the United States.
On January 20, 2017, 
I was sworn in as the 45th president of the United States by Chief Justice of the United States John Roberts. I took the oath of office placing his hand on the Bible that was used at Abraham Lincoln's inauguration and his own family Bible, which was presented to me by my mother in 1955 when I graduated from Sunday school at my family's Presbyterian church.
