### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by LiubovChernohor** [LiubovChernohor/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Andrey7315** [comment]
**LANGUAGES**
 English
**SKILLS** 
Cycling, babysitting, TV presenting, acting, singing, producing, smiling, business, negotiating, counting, betting, command,  keeping.
**CHARACTER** 
Calm, self-assured, competitive, goal-oriented, determined, fun, creative, charming, friendly.
**LIKES** 
Me, money, kids, women, burgers,  sushi, Russia, cycling.
**DISLIKES** 
Porridge, run, name Kim, bulls, stupidity, bald people.
**WEAKNESSES** 
Honesty, justice, women, cookies
